# Generated by Django 2.2.12 on 2020-05-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppointmentForm',
        ),
    ]
