# Generated by Django 2.2.12 on 2020-05-07 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Appointment', '0002_delete_appointmentform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('Phone_no', models.IntegerField()),
                ('case_details', models.TextField(default='')),
                ('adate', models.DateField()),
                ('atime', models.TimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernames', to=settings.AUTH_USER_MODEL)),
                ('lawyer', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
