# Generated by Django 2.2.12 on 2020-05-07 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0003_appointmentform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentform',
            name='lawyer',
            field=models.ManyToManyField(default='', to=settings.AUTH_USER_MODEL),
        ),
    ]
