# Generated by Django 2.2.12 on 2020-05-08 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0004_auto_20200507_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentform',
            name='lawyer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
