# Generated by Django 2.2.12 on 2020-05-08 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0005_auto_20200508_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentform',
            name='Phone_no',
            field=models.BigIntegerField(),
        ),
    ]
