# Generated by Django 2.2.12 on 2020-05-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0006_auto_20200508_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentform',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
