# Generated by Django 2.2.12 on 2020-05-12 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0007_appointmentform_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentform',
            name='lawyer',
            field=models.ManyToManyField(default=0, related_name='lawyers', to=settings.AUTH_USER_MODEL),
        ),
    ]
