# Generated by Django 2.2.12 on 2020-05-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0008_auto_20200512_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentform',
            name='Phone_no',
            field=models.BigIntegerField(default=0),
        ),
    ]
