# Generated by Django 3.0.6 on 2020-07-03 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0009_auto_20200514_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentform',
            name='adate',
            field=models.DateField(default=datetime.datetime(2020, 7, 3, 22, 16, 59, 156297)),
        ),
        migrations.AlterField(
            model_name='appointmentform',
            name='atime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 3, 22, 16, 59, 156312)),
        ),
    ]
