# Generated by Django 3.0.6 on 2020-07-03 22:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0010_auto_20200703_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentform',
            name='adate',
            field=models.DateField(default=datetime.datetime(2020, 7, 3, 22, 30, 24, 302245)),
        ),
        migrations.AlterField(
            model_name='appointmentform',
            name='atime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 3, 22, 30, 24, 302260)),
        ),
        migrations.CreateModel(
            name='notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(default='You have new Appointment Request', max_length=255)),
                ('NfL', models.BooleanField(default=True)),
                ('NfC', models.BooleanField(default=False)),
                ('ndate', models.DateField(default=datetime.datetime(2020, 7, 3, 22, 30, 24, 303425))),
                ('ntime', models.TimeField(default=datetime.datetime(2020, 7, 3, 22, 30, 24, 303440))),
                ('frm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Appointment.AppointmentForm')),
            ],
        ),
    ]
