# Generated by Django 3.0.6 on 2020-07-03 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0012_auto_20200703_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='nusr',
        ),
        migrations.AlterField(
            model_name='appointmentform',
            name='adate',
            field=models.DateField(default=datetime.datetime(2020, 7, 3, 23, 45, 54, 6877)),
        ),
        migrations.AlterField(
            model_name='appointmentform',
            name='atime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 3, 23, 45, 54, 6892)),
        ),
        migrations.AlterField(
            model_name='notify',
            name='ndate',
            field=models.DateField(default=datetime.datetime(2020, 7, 3, 23, 45, 54, 8033)),
        ),
        migrations.AlterField(
            model_name='notify',
            name='ntime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 3, 23, 45, 54, 8048)),
        ),
    ]
