# Generated by Django 3.0.6 on 2020-07-04 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0014_auto_20200704_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentform',
            name='adate',
            field=models.DateField(default=datetime.datetime(2020, 7, 4, 11, 46, 4, 845243)),
        ),
        migrations.AlterField(
            model_name='appointmentform',
            name='atime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 4, 11, 46, 4, 845259)),
        ),
        migrations.AlterField(
            model_name='notify',
            name='ndate',
            field=models.DateField(default=datetime.datetime(2020, 7, 4, 11, 46, 4, 846375)),
        ),
        migrations.AlterField(
            model_name='notify',
            name='ntime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 4, 11, 46, 4, 846393)),
        ),
    ]
