# Generated by Django 3.0.6 on 2020-07-04 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0015_auto_20200704_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentform',
            name='adate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointmentform',
            name='atime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notify',
            name='ndate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notify',
            name='ntime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
