# Generated by Django 3.0.6 on 2020-07-12 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0016_auto_20200704_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentform',
            name='adate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
