# Generated by Django 3.0.6 on 2020-07-12 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Appointment', '0017_auto_20200712_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentform',
            name='adate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
