# Generated by Django 2.2.12 on 2020-05-17 18:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(default='', max_length=120)),
                ('btext', models.TextField(default=' ')),
                ('bpic', models.ImageField(upload_to='Blog/')),
                ('btime', models.TimeField(default=datetime.datetime(2020, 5, 17, 18, 29, 16, 991138, tzinfo=utc))),
                ('bdate', models.DateField(auto_now=True)),
                ('postedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
