# Generated by Django 2.2.12 on 2020-05-18 12:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200517_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2020, 5, 18, 12, 5, 1, 738562, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='addblog',
            name='btime',
            field=models.TimeField(default=datetime.datetime(2020, 5, 18, 12, 5, 1, 738540, tzinfo=utc)),
        ),
    ]
