# Generated by Django 3.0.6 on 2020-07-04 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20200703_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='bdate',
            field=models.DateField(default=datetime.datetime(2020, 7, 4, 11, 26, 53, 843122)),
        ),
        migrations.AlterField(
            model_name='addblog',
            name='btime',
            field=models.TimeField(default=datetime.datetime(2020, 7, 4, 11, 26, 53, 843103)),
        ),
    ]
