# Generated by Django 3.0.6 on 2020-07-04 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_auto_20200704_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblog',
            name='bdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='addblog',
            name='btime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
