# Generated by Django 3.0.6 on 2020-07-20 10:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbox',
            old_name='reciever',
            new_name='receiver',
        ),
        migrations.AddField(
            model_name='chatbox',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
