# Generated by Django 3.0.6 on 2020-07-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SocialCred', '0009_userinfo_pno'),
        ('Questionaire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='uprof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profpicture', to='SocialCred.UserInfo'),
        ),
    ]
