# Generated by Django 3.0.6 on 2020-07-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lawyers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
