# Generated by Django 2.2.12 on 2020-05-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialCred', '0002_auto_20200506_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='speciality',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
