# Generated by Django 2.2.12 on 2020-05-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialCred', '0003_userinfo_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='UserInfo/'),
        ),
    ]
