# Generated by Django 2.2.12 on 2020-05-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialCred', '0004_auto_20200511_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='UserInfo/images'),
        ),
    ]
