# Generated by Django 2.2.12 on 2020-05-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialCred', '0006_auto_20200511_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_picture',
            field=models.ImageField(upload_to='UserInfo/'),
        ),
    ]
